name = "BellDiagonalQudits"
uuid = "33287015-dcc4-41a7-aecb-0a84b862e0d8"
authors = ["Christopher Popp <poppchristopher@pm.me>"]
version = "0.1.0"

[compat]
julia = "1.6.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
